### ISSUE TITLE
issue about “use_hgnc_file”

### ISSUE THREAD

**Issue by ChronoWeaver** [ramiromagno/hgnc#5]
> library(hgnc)
> last_update()
[1] "2023-10-30 03:31:41 UTC"
> use_hgnc_file(file = latest_archive_url())
Error in use_hgnc_file(file = latest_archive_url()) : 
  could not find function "use_hgnc_file"
  

After the r package is loaded correctly, the function cannot be run
  
  I'm using a macbook with m1 chip

**Comment by ramiromagno** [comment]
Hi @Mike-Guo-2021:

Could you run your code inside `reprex::reprex()` (see https://reprex.tidyverse.org/)?

The reason I'm asking this is because I can't reproduce your error.

**Comment by ChronoWeaver** [comment]
``` r
library(hgnc)

# Date of HGNC last update
last_update()
#> [1] "2023-10-30 03:31:41 UTC"

# Set the HGNC archive file to use for the remainder of the R-session
use_hgnc_file(file = latest_archive_url())
#> Error in use_hgnc_file(file = latest_archive_url()): could not find function "use_hgnc_file"
```

<sup>Created on 2023-10-30 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by ramiromagno** [comment]
Could you try installing the development version, please:

```
remotes::install_github("ramiromagno/hgnc")
```

**Comment by ChronoWeaver** [comment]
``` r
library(hgnc)
last_update()
#> [1] "2023-10-30 03:31:41 UTC"
use_hgnc_file(file = latest_archive_url())
#> using hgnc file: https://ftp.ebi.ac.uk/pub/databases/genenames/hgnc/tsv/hgnc_complete_set.txt
```

<sup>Created on 2023-10-31 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

yes, it works.
Thanks for your answer
